// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FileWriter is an autogenerated mock type for the FileWriter type
type FileWriter struct {
	mock.Mock
}

// WriteToFile provides a mock function with given fields: data, dir, location
func (_m *FileWriter) WriteToFile(data string, dir string, location string) error {
	ret := _m.Called(data, dir, location)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(data, dir, location)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
